export const TOKEN_NAME = 'login_status';
export const AUTHENTICATE = '/authenticate';
export const REGISTER_TEXT = 'Need to make an account? Click HERE to register!';
export const REGISTER_BUTTON_TEXT = 'Register';
export const LOGIN_TEXT = 'Click HERE to return to the login page.';
export const LOGIN_BUTTON_TEXT = 'Login';
export const LOGOUT_BUTTON_TEXT = 'Logout';
export const HOME_BUTTON_TEXT = 'Home';
export const LOGIN_BLANK_WARNING = 'The username and password cannot be left blank!';
